CO abs coverage on Pt(100) was θ = 0.77 +/- 0.03

Surface atom density of Pt(100), ρ~Pt(100)~ is 1.503 * 0.866 = 1.302 e 15 atoms/cm^2^

1.302x10^15^ atoms/cm^2^ * 0.77 = 1E15 molecules of CO/cm^2^

Hydrogen coverage at 200 K on Pt(100) 5x20 is 1.1E15 molecules H2/cm^2

Saturation Area from our TPD: 0.318 relative to 1 ML CO area: `sat_CO_area = 2253432`
0.318 is our saturation
So 0.318*1E15 = 3.18E14 molecules of CO / cm^2^

3.18E14/1.302E15 = 0.245 ML of CO relative to surface atomic density, ρ~Pt(100)~

So we have a minimum of 0.122 ML of GUA decomposing because GUA can either form 1 or 2 CO plus O~(ads)~ on the surface
If it forms 1 CO then it is 0.122 ML of GUA decomposing minimum and the maximum is above 0.245 ML of CO


== TO DO:
* Look at https://doi.org/10.1016/S0039-6028(87)80152-8[formaldehyde] or
https://doi.org/10.1016/j.jcat.2016.05.020[methoxide] on surface, which can be found
http://pubs.acs.org/doi/pdf/10.1021/jp400798q[here]

how do they know the amount of phenol on the surface if they don't see a tpd peak? My guess is that they use
6x the C_1s

What if they co-dosed CO until higher exposures? -> doesn't explain carbon on the surface at high temps (fig 2 inset
table)
