= Notes for acetic acid paper

Facts::

- Surface atom density of Ni(110), ρ~Ni(110)~ is 1.864 * 0.612 = 1.141 e 15 atoms/cm^2^

- Saturation CO coverage:

- Saturation H2 coverage:

Comments::

Need to correct for background pressure

arr = [1.5, 1.8, 1, 2.5, 3.2, 3.5, 3.6, 4.9, 6.3, 7.6, 9.1]
L = 1e-6
list(map(lambda x: x*15*1e-9/L, arr))

[0.022500000000000003,
 0.027000000000000003,
 0.015000000000000003,
 0.037500000000000006,
 0.04800000000000001,
 0.052500000000000005,
 0.054000000000000006,
 0.07350000000000001,
 0.09450000000000001,
 0.114,
 0.1365]


Some easy questions

- Do we have H2, CO, and possibly H2O saturation on Ni(110)? Yes
- What are the values for their respective coverages?


High coverage
90 K
•	γ(OH)  at 964 cm-1,  ν(C-O) at 1311 cm-1,  ν(C=O) at 1729 cm-1 suggests molecular acetic acid present on surface
•	Low frequency shoulder ν(C=O) at 1679 cm-1 indicative of catemers5,7
•	δa(CH3) peak at 1419 cm-1,δs(CH3) peak at 1365 cm-1,  ρa(CH3)  at 1056 cm-1, ρs(CH3) at 1022 cm-1
•	νa(OCO) at 1628 cm-1 indicative of monodentate acetate
•	νs(OCO) at 1436 cm-1 indicative of bidentate acetate (why do we have this already?)
•	ν(CH3) peak at 2930 cm-1 and others higher in frequency
•	Peak at 1282? Peak at 1530? Peaks around 2500 cm-1? Peak right above 1792?
200 K
•	Disappearance of γ(OH)  indicating scission of hydroxyl hydrogen
•	Disappearance (or reduction--maybe still there?)   of ν(C-O) at 1311 cm-1
•	 ρa(CH3) less intense and ρs(CH3) less intense (maybe gone)
•	Peak at 1282 cm-1 reduced and 1530 cm-1 gone
•	δs(CH3) (1365 cm-1) peak decreases and shifts to higher wavenumber (more of a shoulder now)
•	δa(CH3) (1419 cm-1) peak sharpens
•	νs(OCO) (1436 cm-1) still present and shifts to 1448 cm-1
•	νa(OCO) still present at 1628 cm-1
•	Peak at 1690 cm-1 (maybe shift of ν(C=O) from 1729 cm-1)
•	Peak right above  at 1792 cm-1 shifts higher, to 1832 cm-1  or  and maybe bridge bonded CO
•	 Peaks around 2578-2900 cm-1 gone
•	ν(CH3) peak at 2930 cm-1  decreases and shifts slightly higher to 2932 cm-1 and others higher in frequency are gone

350 K
•	 ρa(CH3) less intense
•	νs(OCO) grows and becomes very sharp at 1456 cm-1 indicating formation of bidentate
•	δa(CH3) peak still present
•	νa(OCO) disappears indicating monodentate no longer present
•	ν(CH3) peak at 2930 cm-1  still present
•	 bridge bonded ν(CO) peak at 1876 cm-1 (either grows in or shifted from before)
•	Top site ν(CO) peak grows in

450 K
•	All peaks gone except small peaks from νs(OCO) and δa(CH3), maybe ρa(CH3) still present, and broad peak around 950 (probably from background manipulation from us)

Low coverage

90 K
•	no γ(OH)  at 965 cm-1 suggests scission of hydroxyl hydrogen
•	ρa(CH3)  at 1065 cm-1  and ρs(CH3)  at 1028 cm-1 and δa(CH3)  at 1409 cm-1 and δs(CH3) 1340 cm-1 suggests methyl group is intact - this is shifted relative to high coverage δ(CH3) peak.
•	ν(C-O) at 1307 cm-1
•	 νas(OCO)  at 1600 cm-1 indicative of monodentate acetate
•	ν(CO) at 1675 cm-1
•	ν(CH3) modes broad peak centered around ~2950 cm-1 difficult to resolve→ may need to blow up these spectra more to see them

210 K
•	δa(CH3)  at 1409 cm-1 intensifies and sharpens compared to δs(CH3)
•	νs(OCO) peak might start to grow in (may be/is present in the broad δ(CH3) feature)
•	 ρa(CH3)  at 1043 cm-1 is slightly reduced in intensity, but still present
•	Appearance of small ν(CO) feature at 1850 cm-1 on the surface is due to either decomposition of a surface species (such as monodentate acetate) or contamination from background

352 K
•	 δa(CH3) mode decreases
•	 δs(CH3) mode still present
•	νs(OCO) peak at 1456 cm-1 is more intense than δa(CH3) mode
•	νas(OCO)  at 1588 cm-1 disappears
Growth and shift to higher wavenumber of  ν(CO) feature from 1850 cm-1 to 1897 cm-1
